export const AdapterList = [
  {
    name: "mercedes",
    adapter_id: "9b275d489a32",
    adapterVersion: "0",
    queries: [],
  },
  {
    name: "hitachi",
    adapter_id: "3f0e65e72536",
    adapterVersion: "1",
    queries: [
      { Alias: "customerFullName", Text: "What is the first name and surname of customer?" },
      { Alias: "customerAddress", Text: "Where is the address of customer?" },
      { Alias: "supplierName", Text: "What is the name of supplier?" },
      { Alias: "supplierAddress", Text: "What is the address of supplier?" },
      { Alias: "brokerIntermediariesName", Text: "What is the name of broker intermediaries?" },
      { Alias: "brokerIntermediariesAddress", Text: "What is the address of broker intermediaries?" },
      { Alias: "goodsName", Text: "What is the name of goods?" },
      { Alias: "registrationNumber", Text: "What is the registration number?" },
      { Alias: "totalCashPrice", Text: "What is the total cash price?" },
      { Alias: "advancePayment", Text: "What is the advance payment(deposit)?" },
      { Alias: "totalCreditAmount", Text: "What is the Total Amount of Credit?" },
      { Alias: "totalChargeForCredit", Text: "What is the total charge for credit?" },
      { Alias: "interestPrice", Text: "What is the price of interest?" },
      { Alias: "totalAmountPayable", Text: "What is the total amount payable?" },
      { Alias: "APR", Text: "What's the APR?" },
      { Alias: "contractDuration", Text: "How long is the duration of this contract?" },
      { Alias: "signatureDateCustomer", Text: "What is the date of signature customer?" },
      { Alias: "agreementNumber", Text: "What's the agreement number?" },
    ],
  },
  {
    name: "motonovo",
    adapter_id: "4b9b43f9da77",
    adapterVersion: "1",
    queries: [
      { Alias: "customerName", Text: 'What is the name of the customer ("you" or the "customer")?' },
      { Alias: "customerAddress", Text: 'What is the address of the customer ("you" or the "customer")?' },
      { Alias: "creditorName", Text: 'What is the name of the Creditor ("we" or "us" or the "Creditor")?' },
      { Alias: "creditorAddress", Text: 'What is the address of the Creditor ("we" or "us" or the "Creditor")?' },
      { Alias: "creditIntermediaryName", Text: "What's the name of Credit Intermediary?" },
      { Alias: "creditIntermediaryAddress", Text: "What's the address of Credit Intermediary?" },
      { Alias: "securityDescription", Text: "What's the Security of description of goods/services?" },
      { Alias: "chassisSerialNumber", Text: "What's the Chassis/serial number?" },
      { Alias: "registrationNumber", Text: "What's the Registration Number of description of goods servicese?" },
      { Alias: "firstRegistrationDate", Text: "What's the Date of first registration Number of description of goods/servicese?" },
      { Alias: "totalCreditAmount", Text: "How much is the Total Amount of Credit?" },
      { Alias: "cashPrice", Text: "How much is the cash price?" },
      { Alias: "totalPayableAmount", Text: "How much is the Total Amount payable?" },
      { Alias: "partExchangePrice", Text: "How much is the price Part Exchange?" },
      { Alias: "interestPrice", Text: "How much is the price of Interest?" },
      { Alias: "settlementAmountLess", Text: "How much is the price of less Settlement Amount?" },
      { Alias: "adminFeeA", Text: "How much is the Admin Fee part A?" },
      { Alias: "adminFeeB", Text: "How much is the Admin Fee part B?" },
      { Alias: "annualPercentageRate", Text: "What's the Annual Percentage Rate of Charge(APR)?" },
      { Alias: "paymentsAmount", Text: "How much is the Amount of Payments?" },
      { Alias: "goodsServicesMileage", Text: "What's the mileage of description of goods/servicese?" },
      { Alias: "agreementDuration", Text: "How long is the duration of the agreement?" },
      { Alias: "agreementNumber", Text: "What's the Agreement Number of the agreement?" },
      { Alias: "signatureDate", Text: "What's the date of signature(s)?" },
    ],
  },
  {
    name: "honda-finance",
    adapter_id: "70567e4f884e",
    adapterVersion: "1",
    queries: [
      { Alias: "customerName", Text: 'What is the name of the customer ("you")?' },
      { Alias: "customerAddress", Text: 'What is the address of the customer ("you")?' },
      { Alias: "lenderName", Text: 'What is the name of the Lender ("we" or "us" )?' },
      { Alias: "lenderAddress", Text: 'What is the address of the Lender ("we" or "us" )?' },
      { Alias: "creditIntermediaryName", Text: "What's the name of Credit Intermediary?" },
      { Alias: "creditIntermediaryAddress", Text: "What's the address of Credit Intermediary?" },
      { Alias: "goodsMakeModel", Text: "What's the Make/Model of Goods?" },
      { Alias: "goodsVINChassisNumber", Text: "What's the VIN/Chassis No?" },
      { Alias: "goodsRegistrationNumber", Text: "What's the Registration Number of Goods?" },
      { Alias: "goodsFirstRegistrationDate", Text: "What's the first registration Date of Goods?" },
      { Alias: "cashDepositAmount", Text: "How much is the Cash Deposit?" },
      { Alias: "partExchangeAmount", Text: "How much is the Part Exchange?" },
      { Alias: "totalAdvancePayments", Text: "How much Is the Total Advance Payments(d)?" },
      { Alias: "amountOfCredit", Text: "How much is the Amount of Credit (e)?" },
      { Alias: "interestCharges", Text: "How much is the Interest Charges (f)?" },
      { Alias: "totalChargeForCredit", Text: "How much is the Total Charge for Credit [f+g+h]?" },
      { Alias: "totalAmountPayable", Text: "How much is the Total Amount Payable [d+e+k]?" },
      { Alias: "APR", Text: "What's the APR?" },
      { Alias: "monthlyRepaymentPrice", Text: "How much is the price of one repayment payable for 1 months?" },
      { Alias: "finalRepaymentPrice", Text: "How much is the price of the Final repayment?" },
      { Alias: "agreementDuration", Text: "How long is the duration of the agreement?" },
      { Alias: "agreementNumber", Text: "What's the Agreement Number?" },
      { Alias: "signatureDate", Text: "What's the date of signature(s)?" },
      { Alias: "deliveryMileage", Text: "What is the mileage on delivery?" },
    ],
  },
  {
    name: "fca",
    adapter_id: "3fe6aa472c06",
    adapterVersion: "1",
    queries: [
      { Alias: "partyYouName", Text: "What is the name of you of Parties?" },
      { Alias: "partyYouAddress", Text: "What is the address of you of Parties?" },
      { Alias: "partyWeName", Text: "What is the name of we of Parties?" },
      { Alias: "partyWeAddress", Text: "What is the address of we of Parties?" },
      { Alias: "dealerName", Text: "What's the name of Dealer?" },
      { Alias: "dealerAddress", Text: "What's the address of Dealer?" },
      { Alias: "goodName", Text: "What's the name of good?" },
      { Alias: "vinNumber", Text: "What's the VIN number?" },
      { Alias: "goodsRegistrationNumber", Text: "What's the Registration Number of goods?" },
      { Alias: "goodsFirstRegistrationDate", Text: "What's the first registration date of goods?" },
      { Alias: "cashPrice", Text: "How much is the cash price?" },
      { Alias: "totalAmountPayable", Text: "How much is the Total Amount payable?" },
      { Alias: "totalChargeForCredit", Text: "How much is the Total Charge for Credit?" },
      { Alias: "amountOfCredit", Text: "How much is the amount of Credit?" },
      { Alias: "advancePayment", Text: "How much is the Advance Payment?" },
      { Alias: "hpChargesInterest", Text: "How much is the price of HP Charges/Interest?" },
      { Alias: "APR", Text: "What's the APR?" },
      { Alias: "agreementDuration", Text: "How long is the duration of the agreement?" },
      { Alias: "firstPaymentAmount", Text: "How much is the First Payment?" },
      { Alias: "finalPaymentAmount", Text: "How much is the final payment?" },
      { Alias: "agreementNumber", Text: "What's the Agreement Number of the agreement?" },
      { Alias: "signatureDate", Text: "What's the date of signature(s)?" },
    ],
  },
  {
    name: "fce",
    adapter_id: "6fc93a597731",
    adapterVersion: "1",
    queries: [
      { Alias: "customerName", Text: 'What is the name of the customer ("you" or the "customer")?' },
      { Alias: "customerAddress", Text: 'What is the address of the customer ("you" or the "customer")?' },
      { Alias: "creditorName", Text: 'What is the name of the Creditor ("we" or "us" or the "Creditor")?' },
      { Alias: "creditorAddress", Text: 'What is the address of the Creditor ("we" or "us" or the "Creditor")?' },
      { Alias: "dealerName", Text: "What's the name of Dealer?" },
      { Alias: "dealerAddress", Text: "What's the address of Dealer?" },
      { Alias: "goodsMakeModel", Text: "What's the Make/Model of Goods?" },
      { Alias: "goodsChassisVIN", Text: "What's the Chassis/VIN No?" },
      { Alias: "goodsRegistrationNumber", Text: "What's the Registration Number of Goods?" },
      { Alias: "goodsRegistrationDate", Text: "What's the registration Date of Goods?" },
      { Alias: "totalCashPriceGoods", Text: "How much is the (A) Total Cash Price of Goods(inc. any VAT)?" },
      { Alias: "partExchangeAmount", Text: "How much is the Part Exchange?" },
      { Alias: "cashAmount", Text: "How much is the Cash?" },
      { Alias: "amountOfCredit", Text: "How much is the (C)Amount of Credit (A-B)?" },
      { Alias: "chargeOfCredit", Text: "How much is the (D) Charge of Credit?" },
      { Alias: "totalAmountPayable", Text: "How much is the (H)Total Amount payable (B+G)?" },
      { Alias: "APR", Text: "What's the APR?" },
      { Alias: "totalInstalment", Text: "How much is the Total instalment?" },
      { Alias: "agreementMileage", Text: "What's the mileage of Date of Agreement?" },
      { Alias: "agreementDuration", Text: "How long is the duration of the agreement?" },
      { Alias: "fordCreditAccountNumber", Text: "What's the Ford Credit Account No?" },
      { Alias: "signatureDate", Text: "What's the date of signature(s)?" },
    ],
  },
  {
    name: "closebrothers",
    adapter_id: "0dac6f6dbabb",
    adapterVersion: "1",
    queries: [
      { Alias: "customerName", Text: "What is the name of the customer (you)?" },
      { Alias: "customerAddress", Text: "What is the address of the customer (you)?" },
      { Alias: "creditorName", Text: "What is the name of the Creditor (us)?" },
      { Alias: "creditorAddress", Text: "What is the address of the Creditor (us)?" },
      { Alias: "creditIntermediaryName", Text: "What's the name of Credit Intermediary?" },
      { Alias: "creditIntermediaryAddress", Text: "What's the address of Credit Intermediary?" },
      { Alias: "goodsServicesName", Text: "What's the name of description of goods/services?" },
      { Alias: "serialChassisNumber", Text: "What's the Serial/Chassis number?" },
      { Alias: "goodsServicesRegNumber", Text: "What's the Reg. No of description of goods servicese?" },
      { Alias: "goodsServicesFirstRegDate", Text: "What's the Date 1st Reg of description of goods/servicese?" },
      { Alias: "goodsServicesMileage", Text: "What's the mileage of description of goods/servicese?" },
      { Alias: "totalCashPriceGoods", Text: "How much is the Total Cash Price of Goods ( inc VAT ) (a)?" },
      { Alias: "amountOfCredit", Text: "How much is the Amount of Credit?" },
      { Alias: "interestChargesPrice", Text: "How much is the price of Interest Charges?" },
      { Alias: "totalChargeForCredit", Text: "How much is the Total Charge for Credit(b)?" },
      { Alias: "totalAmountPayable", Text: "How much is the Total Amount payable (a+b)?" },
      { Alias: "APR", Text: "What's APR?" },
      { Alias: "monthlyAmount", Text: "How much is the Amount of Monthly?" },
      { Alias: "agreementDurationMonths", Text: "How many months is the duration of the agreement?" },
      { Alias: "agreementNumber", Text: "What's the Agreement Number of the agreement?" },
      { Alias: "signatureDate", Text: "What's the date of signature(s)?" },
    ],
  },
  {
    name: "blackhorse-v1",
    adapter_id: "b518d7dace58",
    adapterVersion: "2",
    queries: [
      { Alias: "customerName", Text: "What is the customer name?" },
      { Alias: "currentAddress", Text: "What is the current address?" },
      { Alias: "goodsRegistrationNumber", Text: "What is the description of goods registration no.?" },
      { Alias: "financialInfoGoodsDuration", Text: "What's the duration month of Financial Information Goods?" },
      { Alias: "creditIntermediaryName", Text: "What is the credit intermediary name?" },
      { Alias: "creditIntermediaryAddress", Text: "What is the address of credit intermediary?" },
      { Alias: "creditName", Text: "What is the credit name?" },
      { Alias: "creditAddress", Text: "What is the credit address?" },
      { Alias: "cashPriceGoods", Text: "How much is the cash price of the goods (A)?" },
      { Alias: "depositLess", Text: "How much is the less deposit (B)?" },
      { Alias: "amountOfCredit", Text: "How much is the amount of credit [(A) - (B)] (C)?" },
      { Alias: "totalChargeForCredit", Text: "How much is the total charge for credit [(i)+(ii)+(iv)] (D)?" },
      { Alias: "total1Repayment", Text: "How much is the total 1 repayment of?" },
      { Alias: "finalRepaymentTotal", Text: "How much is the total (The Final Repayment) of?" },
      { Alias: "APRValue", Text: "What is the APR Value?" },
      { Alias: "dateOfAgreement", Text: "What is the date of agreement?" },
      { Alias: "goodsFirstRegisteredDate", Text: "What is the description of goods date first registered?" },
      { Alias: "goodsName", Text: "What is the description of goods name?" },
      { Alias: "VIN", Text: "What is the VIN?" },
      { Alias: "agreementNumber", Text: "What's the Agreement Number?" },
      { Alias: "totalAmountPayable", Text: "What is the Total Amount Payable?" },
    ],
  },
  {
    name: "bmw",
    adapter_id: "1fd431b2f472",
    adapterVersion: "1",
    queries: [
      { Alias: "lenderName", Text: "Who is the lender?" },
      { Alias: "lenderAddress", Text: "What's the address of lender?" },
      { Alias: "customerName", Text: "What is the customer name?" },
      { Alias: "customerAddress", Text: "What is the customer address?" },
      { Alias: "creditIntermediaryName", Text: "Who is the credit intermediary?" },
      { Alias: "creditIntermediaryAddress", Text: "What is the address of credit intermediary?" },
      { Alias: "vehicleMakeModel", Text: "What is the Make and Model?" },
      { Alias: "vehicleVINChassis", Text: "What is the VIN/chassis?" },
      { Alias: "vehicleFirstRegisteredUK", Text: "When is the first registered of Vehicle in UK?" },
      { Alias: "vehicleRegistrationNumber", Text: "What is the Registration number of Vehicle?" },
      { Alias: "vehicleCashPrice", Text: "How much is the Cash Price of the Vehicle(inc. any VAT)?" },
      { Alias: "advancePaymentAmount", Text: "How much is the Advance Payment?" },
      { Alias: "creditAmount", Text: "How much is the Amount of Credit?" },
      { Alias: "totalChargeForCredit", Text: "How much is the Total Charge for Credit?" },
      { Alias: "totalAmountPayable", Text: "How much is the Total Amount Payable?" },
      { Alias: "agreementDuration", Text: "How long is the duration of the agreement?" },
      { Alias: "firstRepaymentAmount", Text: "How much is the first repayment?" },
      { Alias: "optionalFinalRepayment", Text: "How much is the Optional Final Repayment?" },
      { Alias: "APRValue", Text: "What is the APR?" },
      { Alias: "annualMileage", Text: "What is the Annual Mileage?" },
      { Alias: "maxTotalMileage", Text: "What is the Maximum Total Mileage?" },
      { Alias: "proposalNumber", Text: "What is the Proposal Number?" },
      { Alias: "signatureDate", Text: "When is the date(s) of signature(s)" },
    ],
  },
  {
    name: "vwgroup",
    adapter_id: "aa4a79a924b4",
    adapterVersion: "1",
    queries: [
      { Alias: "firstParty", Text: "Who are the first party of this Agreement?" },
      { Alias: "firstPartyAddress", Text: "Where is the first parties of this Agreement?" },
      { Alias: "secondParty", Text: "Who are the second party of this Agreement?" },
      { Alias: "secondPartyAddress", Text: "Where is the second parties of this Agreement?" },
      { Alias: "dealerCreditIntermediary", Text: "Who is the Dealer action as the credit intermediary?" },
      { Alias: "dealerCreditIntermediaryAddress", Text: "Where is the Dealer action as the credit intermediary?" },
      { Alias: "vehicleCashPrice", Text: "How much is the Vehicle Cash Price?" },
      { Alias: "advancePayment", Text: "How much is the Advance Payment?" },
      { Alias: "amountOfCredit", Text: "How much is the Amount of Credit ?" },
      { Alias: "totalAmountPayable", Text: "What's the total amount payable?" },
      { Alias: "oneRepaymentAmount", Text: "How much is the one repayment?" },
      { Alias: "finalPaymentAmount", Text: "How much is the final payment?" },
      { Alias: "payableDurationMonths", Text: "How many months are for the payable?" },
      { Alias: "APRPercent", Text: "How much is the percent of APR?" },
      { Alias: "signatureDate", Text: "What's the Date of Signature?" },
      { Alias: "agreementNumber", Text: "What's the Agreement Number?" },
      { Alias: "makeModelVariant", Text: "What's the Make/Model and Variant?" },
      { Alias: "registrationDate", Text: "What's the Registration Date?" },
      { Alias: "registrationNumber", Text: "What's the Registration Number?" },
      { Alias: "VINNumber", Text: "What's the VIN number?" },
      { Alias: "maxAnnualMileage", Text: "What's the maximum annual mileage?" },
      { Alias: "maxTotalMileage", Text: "What's the maximum total mileage?" },
    ],
  },
  {
    name: "demo-advantage",
    adapter_id: "9abf280d752c",
    adapterVersion: "2",
    queries: [
      { Alias: "customerName", Text: "What's the name of customer?" },
      { Alias: "customerAddress", Text: "What's the address of customer?" },
      { Alias: "registrationNumber", Text: "What's the registration number?" },
      { Alias: "firstVehicleRegistration", Text: "When's the first registered of Vehicle?" },
      { Alias: "lenderName", Text: "What's the name of lender?" },
      { Alias: "lenderAddress", Text: "What's the address of lender?" },
      { Alias: "creditIntermediaryName", Text: "What's the name of Credit Intermediary?" },
      { Alias: "creditIntermediaryAddress", Text: "What's the address of Credit Intermediary?" },
      { Alias: "totalCashPrice", Text: "How much is the total cash Price of goods?" },
      { Alias: "advancePaymentCash", Text: "How much is the Advance Payment ( Cash )?" },
      { Alias: "advancePaymentPartExchange", Text: "How much is the Advance Payment ( Part Exchange)?" },
      { Alias: "creditAmount", Text: "How much is the amount of credit ?" },
      { Alias: "financeCharges", Text: "How much is the Plus Finance Charges of Interest, Acceptance Fee, Purchase Fee?" },
      { Alias: "totalAmountPayable", Text: "How much is the Total Amount Payable?" },
      { Alias: "APR", Text: "How much is the percent of APR?" },
      { Alias: "agreementDuration", Text: "How many months are the Duration of agreement?" },
      { Alias: "finalMonthPayment", Text: "How much is the final month payment?" },
      { Alias: "monthlyPayments", Text: "How much is the monthly Payments?" },
      { Alias: "lenderSignatureDate", Text: "When was the signature on behalf of the lender made?" },
      { Alias: "agreementNumber", Text: "What's the agreement Number of contract document?" },
      { Alias: "vehicleMakeModel", Text: "What's the Make/Model of vehicle?" },
      { Alias: "vehicleVIN", Text: "What's the VIN number?" },
      { Alias: "financeChargesPlus", Text: "How much is the Plus Finance Charges?" },
    ],
  },
];
